name: Java CI

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Test on Java ${{ matrix.java_version }} and OS ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        java_version: ['11', '13']
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK ${{ matrix.java_version }}
      uses: actions/setup-java@v1.3.0 
      with:
        java-version: ${{ matrix.java_version }}
    - name: Build with Maven
      run: mvn clean verify -B -Pjava8
    - name: Setup GraalVM environment
      uses: DeLaGuardo/setup-graalvm@2.0
      with:
        # The GraalVM version to make available on the path.
        graalvm-version: '19.3.0.java8'
    - name: install native image
      run: gu install native-image
    - name: cd
      run: mvn package -f atomos.tests/service.substrate/pom.xml
      
